"""WinPyAI configuration constants."""

APP_NAME = "WinPyAI"
APP_VERSION = "1.0.0"
OLLAMA_HOST = "http://localhost:11434"
DEFAULT_MODEL = "llama3.2:latest"
DB_PATH = "winpyai.db"
MAX_CHAT_WIDTH = 800
MESSAGE_BUBBLE_RADIUS = 12
USER_COLOR = "#2B2B2B"
ASSISTANT_COLOR = "#1A1A2E"
USER_BUBBLE_BORDER = "#3A3A3A"
ASSISTANT_BUBBLE_BORDER = "#2A2A4E"
ACCENT_COLOR = "#10A37F"  # ChatGPT green accent
ACCENT_HOVER = "#0D8C6D"
BG_PRIMARY = "#1E1E1E"      # Main background
BG_SECONDARY = "#2D2D2D"    # Sidebar, inputs
BG_TERTIARY = "#3D3D3D"     # Hover states
TEXT_PRIMARY = "#ECECEC"
TEXT_SECONDARY = "#9B9B9B"
TEXT_DISABLED = "#6B6B6B"
BORDER_COLOR = "#4A4A4A"
FONT_FAMILY = "Segoe UI"
FONT_SIZE_NORMAL = 14
FONT_SIZE_SMALL = 12
FONT_SIZE_TITLE = 16
SCROLLBAR_WIDTH = 8
